/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminCacheData: typeof import('./src/components/AdminCacheData.vue')['default']
    AdminCacheInfo: typeof import('./src/components/AdminCacheInfo.vue')['default']
    AdminData: typeof import('./src/components/AdminData.vue')['default']
    AdminDatas: typeof import('./src/components/AdminDatas.vue')['default']
    AdminInfos: typeof import('./src/components/AdminInfos.vue')['default']
    AdminNav: typeof import('./src/components/AdminNav.vue')['default']
    AdminSystemInfo: typeof import('./src/components/AdminSystemInfo.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    State: typeof import('./src/components/State.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
  }
}
